<org.uberfire.java.nio.base.Properties serialization="custom">
  <unserializable-parents/>
  <map>
    <default>
      <loadFactor>0.75</loadFactor>
      <threshold>12</threshold>
    </default>
    <int>16</int>
    <int>3</int>
    <string>discuss.note[0]</string>
    <string>Is this the correct rate?</string>
    <string>discuss.ts[0]</string>
    <long>1413904401067</long>
    <string>discuss.author[0]</string>
    <string>quickstartUser</string>
  </map>
</org.uberfire.java.nio.base.Properties>