package com.ibm.cpo.projects.shippingproject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(080f5d78b38b2f828ff6252d0f58c9e2)
 */
public class AllinOneShipping  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigDecimal orderPrice;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String state;

    public AllinOneShipping() {
    }

    public AllinOneShipping(java.lang.String state, java.math.BigDecimal orderPrice) {
        this.state = state;
        this.orderPrice = orderPrice;
    }


    
    public java.math.BigDecimal getOrderPrice() {
        return this.orderPrice;
    }

    public void setOrderPrice(java.math.BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
}