package com.ibm.cpo.projects.shippingproject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(980bbb125db005bafa35d7368d3654e9)
 */
public class OrderInfo extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String itemCode;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Short itemQuantity;
    
    @org.kie.api.definition.type.Position(value = 2)
    private double orderPrice;

    public OrderInfo() {
    }

    public OrderInfo(java.lang.String itemCode, java.lang.Short itemQuantity, double orderPrice) {
        this.itemCode = itemCode;
        this.itemQuantity = itemQuantity;
        this.orderPrice = orderPrice;
    }


    
    public java.lang.String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(java.lang.String itemCode) {
        this.itemCode = itemCode;
    }
    
    public java.lang.Short getItemQuantity() {
        return this.itemQuantity;
    }

    public void setItemQuantity(java.lang.Short itemQuantity) {
        this.itemQuantity = itemQuantity;
    }
    
    public double getOrderPrice() {
        return this.orderPrice;
    }

    public void setOrderPrice(double orderPrice) {
        this.orderPrice = orderPrice;
    }
}