package com.ibm.cpo.projects.shippingproject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(033e4d9f303a8acf94c4461b80bc82e4)
 */
public class ShippingObject  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private com.ibm.cpo.projects.shippingproject.ShippingAddress customerAddress;
    
    @org.kie.api.definition.type.Position(value = 1)
    private com.ibm.cpo.projects.shippingproject.OrderInfo orderDetails;

    public ShippingObject() {
    }

    public ShippingObject(com.ibm.cpo.projects.shippingproject.ShippingAddress customerAddress, com.ibm.cpo.projects.shippingproject.OrderInfo orderDetails) {
        this.customerAddress = customerAddress;
        this.orderDetails = orderDetails;
    }


    
    public com.ibm.cpo.projects.shippingproject.ShippingAddress getCustomerAddress() {
        return this.customerAddress;
    }

    public void setCustomerAddress(com.ibm.cpo.projects.shippingproject.ShippingAddress customerAddress) {
        this.customerAddress = customerAddress;
    }
    
    public com.ibm.cpo.projects.shippingproject.OrderInfo getOrderDetails() {
        return this.orderDetails;
    }

    public void setOrderDetails(com.ibm.cpo.projects.shippingproject.OrderInfo orderDetails) {
        this.orderDetails = orderDetails;
    }
}