package com.ibm.cpo.projects.shippingproject;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(5ffbb609c92ed13382476915a05b2434)
 */
public class ShippingAddress  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String street;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String zip;

    public ShippingAddress() {
    }

    public ShippingAddress(java.lang.String name, java.lang.String street, java.lang.String city, java.lang.String state, java.lang.String zip) {
        this.name = name;
        this.street = street;
        this.city = city;
        this.state = state;
        this.zip = zip;
    }


    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getStreet() {
        return this.street;
    }

    public void setStreet(java.lang.String street) {
        this.street = street;
    }
    
    public java.lang.String getZip() {
        return this.zip;
    }

    public void setZip(java.lang.String zip) {
        this.zip = zip;
    }
}